### ISSUE TITLE
Problem running script

### ISSUE THREAD

**Issue by mOoisaCoW** [matthew-kyles/CWA_Password_Extractor#2]
I can't get this to run with the latest version of Automate 2024.3 (Patch 3).
I have obtained the Client ID and Bearer tokens from the developer tools in a web login.  Below is how I ran the command and the output.  The only difference is the client ID and bearer token have been replaced with random value's and the base URL I used points to the Automate server where HTTPS access is valid

python CW_Automate_PW_Extractor.py --clientid '1a8c3e7f-2b1d-4e9a-8f6c-9d0e0adcc8e7' --bearer_token 'bearer Xn9krbN7QfCmYLdJJ88P9w==' --base_url 'https://changed.com' --output_file 'cwa_passwords.csv'
usage: CW_Automate_PW_Extractor.py [-h] [--clientid N] [--bearer_token N] [--base_url N] [--output_file N]
CW_Automate_PW_Extractor.py: error: unrecognized arguments: Xn9krbN7QfCmYLdJJ88P9w=='

If I remove the word bearer from the bearer token I then get the following where the URL looks to be single quoted incorrectly?
python CW_Automate_PW_Extractor.py --clientid '1a8c3e7f-2b1d-4e9a-8f6c-9d0e0adcc8e7' --bearer_token 'Xn9krbN7QfCmYLdJJ88P9w==' --base_url 'https://PrivateAndPublicURL.com' --output_file 'cwa_passwords.csv'
Traceback (most recent call last):
  File "C:\Users\Michael\Downloads\CW_Automate_PW_Extractor.py", line 21, in <module>
    cwclientids = requests.get(clientsurl, headers=headers)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 697, in send
    adapter = self.get_adapter(url=request.url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 794, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for "'https://PrivateAndPublicURL.com'/cwa/api/v1/clients?pageSize=-1&includeFields=Name&orderBy=Name%20asc"

Any suggestions?   I am IT generalist with coding not my strong suit
Time based MFA is enabled on my login - which I believe has to be these days.  Could this be a factor?

**Comment by matthew-hoad** [comment]
Thanks for reaching out. I wonder if calling the script without quotes around the `base_url` value would make a difference? This error typically means that the requests library can't parse the protocol/URL properly and it does seem like the base part of the URL here is being single-quoted.
I will take a look later today to see if I can refactor things a bit to be more reliable. I am much better at writing reliable Python now than I was back when I first wrote this thing 😅

**Comment by mOoisaCoW** [comment]
Thanks Matt for looking into this
I just tested it without quotes around it like you suggested.   It gave the following (I'm running out the door so didn't check to see if the bearer token or client id's had changed in the browser):
python CW_Automate_PW_Extractor.py --clientid '1a8c3e7f-2b1d-4e9a-8f6c-9d0e0adcc8e7' --bearer_token 'Xn9krbN7QfCmYLdJJ88P9w==' --base_url https://changed.com --output_file 'cwa_passwords.csv'
Traceback (most recent call last):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michael\Downloads\CW_Automate_PW_Extractor.py", line 22, in <module>
    cwclientids = pd.DataFrame(cwclientids.json())
                               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by matthew-hoad** [comment]
Also the first "B" in "Bearer xxxxxxxxx" is supposed to be capitalised I think? This is incorrect in the script's help text for that arg

**Comment by mOoisaCoW** [comment]
Hey Matthew.  I have tried a number of variations that still unfortunately didn't work with it not recognizing the bearer token:

python CW_Automate_PW_Extractor.py --clientid '1a8c3e7f-2b1d-4e9a-8f6c-9d0e0adcc8e7' --bearer_token 'Bearer QvUrXnGiDECLLIYXhDpKXA==' --base_url https://PrivateAndPublicURL.com --output_file 'cwa_passwords.csv'
usage: CW_Automate_PW_Extractor.py [-h] [--clientid N] [--bearer_token N] [--base_url N] [--output_file N]
CW_Automate_PW_Extractor.py: error: unrecognized arguments: QvUrXnGiDECLLIYXhDpKXA=='

python CW_Automate_PW_Extractor.py --clientid '1a8c3e7f-2b1d-4e9a-8f6c-9d0e0adcc8e7' --bearer_token 'bearer QvUrXnGiDECLLIYXhDpKXA==' --base_url https://PrivateAndPublicURL.com --output_file 'cwa_passwords.csv'
usage: CW_Automate_PW_Extractor.py [-h] [--clientid N] [--bearer_token N] [--base_url N] [--output_file N]
CW_Automate_PW_Extractor.py: error: unrecognized arguments: QvUrXnGiDECLLIYXhDpKXA=='

python CW_Automate_PW_Extractor.py --clientid '1a8c3e7f-2b1d-4e9a-8f6c-9d0e0adcc8e7' --bearer_token ''bearer QvUrXnGiDECLLIYXhDpKXA==' --base_url https://PrivateAndPublicURL.com --output_file 'cwa_passwords.csv'
usage: CW_Automate_PW_Extractor.py [-h] [--clientid N] [--bearer_token N] [--base_url N] [--output_file N]
CW_Automate_PW_Extractor.py: error: unrecognized arguments: QvUrXnGiDECLLIYXhDpKXA=='

python CW_Automate_PW_Extractor.py --clientid '1a8c3e7f-2b1d-4e9a-8f6c-9d0e0adcc8e7' --bearer_token bearer Xn9krbN7QfCmYLdJJ88P9w== --base_url https://PrivateAndPublicURL.com --output_file 'cwa_passwords.csv'
usage: CW_Automate_PW_Extractor.py [-h] [--clientid N] [--bearer_token N] [--base_url N] [--output_file N]
CW_Automate_PW_Extractor.py: error: unrecognized arguments: Xn9krbN7QfCmYLdJJ88P9w==

python CW_Automate_PW_Extractor.py --clientid '1a8c3e7f-2b1d-4e9a-8f6c-9d0e0adcc8e7' --bearer_token Bearer Xn9krbN7QfCmYLdJJ88P9w== --base_url https://PrivateAndPublicURL.com --output_file 'cwa_passwords.csv'
usage: CW_Automate_PW_Extractor.py [-h] [--clientid N] [--bearer_token N] [--base_url N] [--output_file N]
CW_Automate_PW_Extractor.py: error: unrecognized arguments: Xn9krbN7QfCmYLdJJ88P9w==

If I get rid of the bearer before the token it then gives - does this mean it's getting further?:
python CW_Automate_PW_Extractor.py --clientid '1a8c3e7f-2b1d-4e9a-8f6c-9d0e0adcc8e7' --bearer_token Xn9krbN7QfCmYLdJJ88P9w== --base_url https://PrivateAndPublicURL.com --output_file 'cwa_passwords.csv'
Traceback (most recent call last):
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Michael\Downloads\CW_Automate_PW_Extractor.py", line 22, in <module>
    cwclientids = pd.DataFrame(cwclientids.json())
                               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by imamuppet** [comment]
Thanks for the script Matthew!  Can confirm still working.

mOoisaCoW, I was having same issues you were, but it ended up just needing to quote the bearer, and remove the ' from the elements.   Below worked for me, (changed values obv)

py c:\CW_Automate_PW_Extractor.py --clientid abcdefg --bearer_token "bearer abcdef==" --base_url https://test.test.com --output_file 'cwa_passwords.csv'

**Comment by mOoisaCoW** [comment]
> Thanks for the script Matthew! Can confirm still working.
> 
> mOoisaCoW, I was having same issues you were, but it ended up just needing to quote the bearer, and remove the ' from the elements. Below worked for me, (changed values obv)
> 
> py c:\CW_Automate_PW_Extractor.py --clientid abcdefg --bearer_token "bearer abcdef==" --base_url https://test.test.com --output_file 'cwa_passwords.csv'

Much appreciated @imamuppet     I have confirmed that worked perfectly for me too!     Thank you for the script @matthew-hoad 
For anyone else I found it easiest to get the bearer_token and clientid using firefox's developer tools - plus I haven't tested but the quotes on the output file are probably not needed as they get written to the file name.

**Comment by ipswitch8** [comment]
I dunno if this is still being maintained, but a few things have changed in more recent editions of the webclient, as follows:
- besides the Authorization bearer value in the header, it also needs a Correlation-Id, both of these change every 10min or so
- syntax of misc things has changed a bit, (URLs, response content etc)
- the server wants to see more of the standard headers, including things like Referrer, User-Agent etc

So here's a somewhat re-written version, which includes All The Headers (because it was easier), a couple more command-line parameters, as well as some comments where I moved/changed things around a wee bit so it can be compared to previous code, (e.g. if somebody has an in-between version of LT between OP's and this):

`#Begin new and improved CW/LT/Automate pwd extractor
#Example commandline with the new parameters (I have python3, and no these aren't real values :)
#python3 CWA_Password_Extractor.py --correlation 77495c4e-272d-43e6-b8bc-f44c577d39b8 --clientnum 77 --clientid 6d4a6b99-5305-4574-9aba-44b0deede695 --bearer_token "bearer 6YcIocSzQEyq5iJGyQZ7IA==" --base_url https://rmm.yourmsp.xyz --output_file ./this_customer_passwords.csv

import requests
import pandas as pd
import argparse
import csv
from urllib.parse import urlparse

parser = argparse.ArgumentParser()
parser.add_argument("--cookie", dest="cookie", metavar="N", type=str, help="the Cookie", )
parser.add_argument("--correlation", dest="correlation", metavar="N", type=str, help="the Correlation ID", )
parser.add_argument("--clientnum", dest="clientnum", metavar="N", type=str, help="the customer Client number, (e.g. 133, or 257 etc", )
parser.add_argument("--clientid", dest="clientid", metavar="N", type=str, help="the ClientID for this API/session (not your customer)", )
parser.add_argument("--bearer_token", dest="bearer_token", metavar="N", type=str, help="The bearer token in the format 'bearer asdfasdfasdfasdf'")
parser.add_argument("--base_url", dest="base_url", metavar="N", type=str, help="the org URL, E.g. 'https://myorg.hostedrmm.com'")
parser.add_argument("--output_file", dest="output_file", metavar="N", type=str, help="The name of the csv file to output to, E.g. 'cwa_passwords.csv'")
args = parser.parse_args()

parsed_url = urlparse(args.base_url)
hostname = parsed_url.netloc

headers = {
    "Accept": "application/json, text/plain, */*",
    "Accept-encoding" : "gzip, deflate, br, zstd",
    "Accept-language" : "en-US,en;q=0.9",
    "Authorization": args.bearer_token,
    "Clientid": args.clientid,
    "Connection" : "keep-alive",
    "Cookie" : args.cookie,
    "Correlation-Id" : args.correlation,
    "Dnt" : "1",
    "Host" : hostname,
    "Referer" : f"{args.base_url}/automate/browse/companies/company-passwords?companyId={args.clientnum}",
    "Sec-ch-ua" : '"Chromium";v="128", "Not;A=Brand";v="24", "Brave";v="128"',
    "Sec-ch-ua-mobile" : "?0",
    "Sec-ch-ua-platform" : '"Linux"',
    "Sec-fetch-dest" : "empty",
    "Sec-fetch-mode" : "cors",
    "Sec-fetch-site" : "same-origin",
    "Sec-gpc" :    "1",
    "User-agent" : "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"    
}

#clientsurl = f"{args.base_url}/cwa/api/v1/clients?pageSize=-1&includeFields=Name&orderBy=Name%20asc"
clientsurl = f"{args.base_url}/cwa/api/v1/clients/{args.clientnum}/deploymentlogins?pagesize=200&page=1&condition=&orderBy=title%20asc"

print(f"\nList URL: {clientsurl}\n")
print(f"\nHeaders: {headers}\n")

cwclientids = requests.get(clientsurl, headers=headers)
cwloginids = pd.DataFrame(cwclientids.json())

#This is in the loop now, for convenience...
#Old URL
#deploymentloginidsurl = "/cwa/api/v1/clients/{cwclientid}/deploymentlogins?pagesize=-1&condition=&orderBy=title%20asc&includeFields=password,Username,Title,Notes,Url"
#New URL
#deploymentloginidsurl = "/cwa/api/v1/clients/{args.clientnum}/deploymentlogins?pagesize=1&page=1&condition=DeploymentLoginId={custloginid}&includeFields=password"

jsonlist = []
for loginid in cwloginids['DeploymentLoginId'].values:

    #From above, with modifications to simplify requests.get syntax below, since I am a Python n00b and it wasn't cooperating with my changes...
    deploymentloginidsurl = args.base_url+"/cwa/api/v1/clients/"+args.clientnum+"/deploymentlogins?pagesize=1&page=1&condition=DeploymentLoginId="+str(loginid)+"&includeFields=password"

    #Uncomment for sanity-checking, or if you just want to see it scroll...
    #print(f"\nLogin {loginid}: {deploymentloginidsurl}\n")

    #Simple is good!
    resp = requests.get(deploymentloginidsurl, headers=headers)
    if resp.status_code not in [200, 201, "200", "201"]:
        print(f"Failed to get password for login id {loginid}")
        continue
    jsonlist += resp.json()

df = pd.DataFrame(jsonlist)

#Little bit of flattening for visual convenience...
df['ClientId'] = df['Client'].apply(lambda x: x['ClientId'])

#Uncomment for sanity-checking array contents
#print(df)

#More flattening...
cwloginids['Client'] = cwloginids['Client'].apply(lambda x: x['Name'])

#Uncomment for sanity-checking array contents
#print(cwloginids)

#I've never touched Python or Panda before and found the manual merge in the previous code confusing, so removing these...
#df['ClientId'] = df['Client'].apply(lambda x: x['ClientId'])
#df['ClientName'] = df['Client'].apply(lambda x: cwloginids.loc[cwloginids['DeploymentLoginId'] == str(x['ClientId'])]['Name'].values[0])
#df = df[["ClientName", "ClientId","Title", "Username", "Password", "Notes", "Url"]]

#...in favor of native Panda merge
merged_df = pd.merge(df, cwloginids, on='DeploymentLoginId', how='inner')

#If you want to actually drop columns instead of eliding in the csv output command below... 
#merged_df = merged_df.drop(['DeploymentLoginId', 'Client_x', 'ClientId'], axis=1)

#...but be aware some columns don't exist in some records!  (If these are important to you then you'll need to check for them when you output, I didn't bother, you can figure it out.  :)
#if 'Location' in merged_df.columns:
####merged_df = merged_df.drop(['Location'], axis=1)
 
#Because the Panda merge doesn't know what to do with duplicate column names we get some extra bits, might as well make them nicer while we're doing cleanup here...
merged_df.rename(columns={'Client_y': 'ClientName'}, inplace=True)

#Uncomment for sanity-checking array contents
#print(merged_df)

#Added some options to help with outputs that have lots of complicated notes, and also fix the post-merge column order
#df.to_csv(args.output_file, index=False)
merged_df.to_csv(args.output_file, index=False, quoting=csv.QUOTE_ALL, columns=['ClientName','Title','Url','Username','Password','Notes'])

#Done!`

HTH some more CW refugees!  :)

Also sorry for slightly funky commenting syntax, Github kept trying to be fancy with them in ways that would make it hard for somebody to just copy/pasta.  :/

**Comment by matthew-hoad** [comment]
@ipswitch8 I haven't been maintaining it honestly, but I love the changes you're suggesting. Feel free to create a PR with those changes and I'll take a look at merging it 🔥

**Comment by ipswitch8** [comment]
@matthew-hoad - Haha, didn't want to bother you, but since you responded...  :P  

(Might be a sec, I'm not normally a Github user either, this is just a random old account I logged in to make the comment, lol.)

Umm, yeah, okay, that's going to be a whole thing - probably 2sec for a Github native, but maybe 2hrs for me since I'm a Github naif!  

But, umm, feel free to pick through the code above?  
There's nothing fancy, if anything it's actually a bit simpler, (like me!  :)

(And thanks so much for being the giant upon whose shoulders I got to stand!)
